server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shcfighter/spring-cloud.git
          searchPaths: cloud-config-repo
  application:
    name: cloud-config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud1.com:8761/eureka/,http://springcloud2.com:8761/eureka/,http://springcloud3.com:8761/eureka/

management:
  security:
    enabled: false
