spring:
#  cloud:
#    config:
#      uri: http://192.168.1.57:${config.port:8888}
#      name: simple-ui
#      profile: ${config.profile:dev}
  application:
      name: cloud-simple-ui

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.57:8761/eureka/
      #defaultZone: http://springcloud1.com:8761/eureka/,http://springcloud2.com:8761/eureka/,http://springcloud3.com:8761/eureka/

cloud-simple-service:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 10000

server:
  port: 8090


#启动feign的hystrix
feign:
  hystrix:
    enabled: true