server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shcfighter/spring-cloud.git
          searchPaths: cloud-config-repo
  application:
    name: cloud-config-server
  #rabbitmq:
    #host: 192.168.101.148
    #port: 5672
    #username: admin
    #password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
