spring:
  cloud:
    config:
      uri: http://192.168.101.134:${config.port:8888}
      name: simple-service
      profile: ${config.profile:dev}
  application:
    name: cloud-simple-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.134:8761/eureka/,http://192.168.101.135:8761/eureka/

management:
  security:
    enabled: false


