spring:
  cloud:
    config:
      uri: http://192.168.197.251:${config.port:8888}
      name: simple-service
      profile: ${config.profile:dev}
  application:
    name: cloud-simple-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.197.251:8761/eureka/
server:
  port: 8081
management:
  security:
    enabled: false