logging:
  level.org.springframework.cloud: DEBUG
  
server: 
  port: 8080

spring:
  application:
    name: cloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud1.com:8761/eureka/,http://springcloud2.com:8761/eureka/,http://springcloud3.com:8761/eureka/


zuul:
  routes:
    user:
      path: /user/**
      #strPrefix: true
      serviceId: cloud-simple-ui

#zuul.routes.orgservice.path=/org/**
#zuul.routes.orgservice.strPrefix=true
#zuul.routes.orgservice.url=http://localhost:9002/org
