spring:
  cloud:
    config:
      uri: http://localhost:${config.port:8888}
      name: simple-ui-feign
      profile: ${config.profile:dev}
  application:
      name: cloud-simple-ui-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud4.com:8761/eureka/
      #defaultZone: http://springcloud1.com:8761/eureka/,http://springcloud2.com:8761/eureka/,http://springcloud3.com:8761/eureka/

server:
  port: 8090

management:
  security:
    enabled: false

#启动feign的hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true