server:
  port: 8761
eureka:
  instance:  
    hostname: springcloud3.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://springcloud1.com:8761/eureka/,http://cloudcloud2.com:8761/eureka/,http://cloudcloud3.com:8761/eureka/

spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: false