server:
  port: 8761
eureka:
  instance:  
    hostname: localhost
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: false