server:
  port: 8761
eureka:
  instance:  
    hostname: springcloud3.com
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://springcloud2.com:8761/eureka/,http://springcloud1.com:8761/eureka/

spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: false