server:
  port: 8761
eureka:
  instance:  
    hostname: springcloud1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://springcloud1:8761/eureka/,http://cloudcloud2:8761/eureka/,http://cloudcloud3:8761/eureka/

spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: false