server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.101.134
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.101.134:${server.port}/eureka/,http://192.168.101.134:${server.port}/eureka/
  server:
    evictionIntervalTimerInMs: 1000

spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: false