server:
  port: 8761
eureka:
  instance:  
    hostname: 192.168.101.154
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.101.154:8761/eureka/,http://192.168.101.154:8762/eureka/,http://192.168.101.154:8763/eureka/

spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: false