server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.101.134
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: cloud-eureka-server
management:
  security:
    enabled: true