spring:
  datasource:
    url: jdbc:mysql://springcloud1.com:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KgcDNXnxP2!
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 10
      max-idle: 50
      max-active: 100
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 5000
      validation-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapperLocations: classpath:cloud/simple/*/mapper/*.xml
  typeAliasesPackage: cloud.simple.*.model

server:
  port: 8081

management:
  security:
    enabled: false

bus:
  user: zhangsan